#include "flex_mxml_operations.h"
#include <stdio.h>
#include <string.h>
#include <glib/gprintf.h>
#include <libxml/encoding.h>

// check, if libxml2 library was compiled with needed functionality, else stop compilation with error message
#ifndef LIBXML_WRITER_ENABLED
	#error libxml2 was compiled without LIBXML_WRITER_ENABLED. This flags needed to generate mxml files
#endif

#ifndef LIBXML_OUTPUT_ENABLED
	#error libxml2 was compiled without LIBXML_OUTPUT_ENABLED. This flags needed to generate mxml files
#endif

#define XML_FILE_ENCODING "UTF-8" // use UTF-8 codepage in xml files as default codepage


xmlDocPtr flex_mxml_create_document() {
	/*
     * init libxml2 library
     */
	LIBXML_TEST_VERSION

    gint rc;
    xmlTextWriterPtr writer;
    xmlChar *tmp;
    xmlDocPtr doc;

    /* Create a new XmlWriter for uri, with no compression. */
    writer = xmlNewTextWriterDoc(&doc, 0);
    if (writer == NULL) {
    	g_critical("testXmlwriterFilename: Error creating the xml writer\n");
		return 0;
    }

    /* Start the document with the xml default for the version,
     * encoding and the default for the standalone
     * declaration. */
    rc = xmlTextWriterStartDocument(writer, NULL, XML_FILE_ENCODING, NULL);
    if (rc < 0) {
    	g_critical ("testXmlwriterFilename: Error at xmlTextWriterStartDocument\n");
		return 0;
    }

    /* Start an element named "mx:Application". Since thist is the first
     * element, this will be the root element of the document */
    rc = xmlTextWriterStartElement(writer, BAD_CAST "mx:Application");
    if (rc < 0) {
    	g_critical ("testXmlwriterFilename: Error at xmlTextWriterStartElement\n");
    	return 0;
    }

    /* Add an attribute with name "xmlns:mx" and value "http://www.adobe.com/2006/mxml" to ORDER. */
    rc = xmlTextWriterWriteAttribute(writer, BAD_CAST "xmlns:mx",
                                     BAD_CAST "http://www.adobe.com/2006/mxml");
    if (rc < 0) {
    	g_critical("testXmlwriterDoc: Error at xmlTextWriterWriteAttribute\n");
        return 0;
    }

    /*rc = xmlTextWriterWriteElement(writer, BAD_CAST "NAME_1", "asfshfasfasf");
    if (rc < 0) {
    	g_printf("testXmlwriterDoc: Error at xmlTextWriterWriteElement\n");
    	return 0;
    }*/

    /* Add comments to mxml, that mxml file was generated by salasaga project. */
    rc = xmlTextWriterWriteComment(writer,"This xml file generated using salasaga ide");
    if (rc < 0) {
    	g_critical ("testXmlwriterDoc: Error at xmlTextWriterWriteComment\n");
    	return;
    }

    /* Close the element named mx:Application. */
    rc = xmlTextWriterEndElement(writer);
    if (rc < 0) {
    	g_critical("testXmlwriterDoc: Error at xmlTextWriterEndElement\n");
		return 0;
    }

    /* Here we could close the all unclosed elements using the
     * function xmlTextWriterEndElement, but since we do not want to
     * write any other elements, we simply call xmlTextWriterEndDocument,
     * which will do all the work. */
    rc = xmlTextWriterEndDocument(writer);
    if (rc < 0) {
    	g_critical("Error at xmlTextWriterEndDocument");
    	return 0;
    }

    xmlFreeTextWriter(writer);

    //xmlSaveFileEnc(filepathname, doc, XML_FILE_ENCODING);
    return doc;
}

void flex_mxml_file_save(xmlDocPtr doc,gchar* filepathname) {
	// save DOM to file
	xmlSaveFile(filepathname, doc);
}

void flex_mxml_close_document(xmlDocPtr doc) {
	xmlFreeDoc(doc);
	xmlCleanupParser();
}

gint flex_mxml_compile_to_swf(gchar* source_mxml_filename, gchar* destination_swf_filename,flex_mxml_compilation_flash_options_t* swf_options) {
	// prepare mxml compiller flags
	GString* mxml_compiller_parameters = g_string_sized_new(50);

	g_string_append_printf(mxml_compiller_parameters, "mxmlc %s -output %s ",source_mxml_filename, destination_swf_filename);

	// set additional options to mxmlc compiller
	if (swf_options != 0) {
		if (swf_options->framerate > 0 && swf_options->framerate < 64) {
			g_string_append_printf(mxml_compiller_parameters, "-default-frame-rate %i ", swf_options->framerate);
		}
		if (swf_options->width > 0 && swf_options->height > 0) {
			g_string_append_printf(mxml_compiller_parameters, "-default-size %i %i ", swf_options->width, swf_options->height);
		}
		if (swf_options->title != NULL) {
			g_string_append_printf(mxml_compiller_parameters, "-title %s ", swf_options->title->str);
		}
		if (swf_options->description != NULL) {
			g_string_append_printf(mxml_compiller_parameters, "-description %s ", swf_options->description->str);
		}
		if (swf_options->publisher != NULL) {
			g_string_append_printf(mxml_compiller_parameters, "-publisher %s ", swf_options->publisher->str);
		}
		if (swf_options->creator != NULL) {
			g_string_append_printf(mxml_compiller_parameters, "-creator %s ", swf_options->creator->str);
		}
		if (swf_options->language != NULL) {
			g_string_append_printf(mxml_compiller_parameters, "-language+=%s ", swf_options->language->str);
		}
	}
	g_debug("run mxmlc : %s\n", mxml_compiller_parameters->str);

	GError* error = NULL;
	gchar* stdout;
	gchar* stderr;
	gint exit_status;
	int return_value = 0;

	// call mxmlc using PATH environment variable
	if (!g_spawn_command_line_sync(mxml_compiller_parameters->str, &stdout, &stderr,&exit_status,&error)) {
		g_critical("%s",error->message);
		g_string_free(mxml_compiller_parameters,1);
		return 0;
	}

	#ifdef FLEX_DIR
	}
	#endif

	g_printf("%s\n%s\n", stdout,stderr);

	if (exit_status != 0) {
		return return_value = -1;
	}

	g_free(stdout);
	g_free(stderr);

	g_string_free(mxml_compiller_parameters,1);

	return return_value;
}

flex_mxml_compilation_flash_options_t* flex_mxml_compilation_flash_options_create() {
	flex_mxml_compilation_flash_options_t* flash_options = g_malloc(sizeof(flex_mxml_compilation_flash_options_t));

	memset(flash_options, 0, sizeof(flex_mxml_compilation_flash_options_t));

	flash_options->creator = g_string_new("Salasaga");

	return flash_options;
}

void flex_mxml_compilation_flash_options_delete(flex_mxml_compilation_flash_options_t* flash_options) {
	if (flash_options->title) {
		g_string_free(flash_options->title,1);
	}
	if (flash_options->description) {
		g_string_free(flash_options->description,1);
	}
	if (flash_options->creator) {
		g_string_free(flash_options->creator,1);
	}
	if (flash_options->publisher) {
		g_string_free(flash_options->publisher,1);
	}
	if (flash_options->language) {
		g_string_free(flash_options->language,1);
	}

	g_free(flash_options);
}
