include Makefile.config

DESKTOP_FILE = \
	salasaga.desktop

FONT_BITSTREAM_VERA_FDB = \
	"Bitstream Vera Sans Mono-B-I.fdb" \
	"Bitstream Vera Sans Mono-B.fdb" \
	"Bitstream Vera Sans Mono-I.fdb" \
	"Bitstream Vera Sans Mono.fdb" \
	"Bitstream Vera Sans-B-I.fdb" \
	"Bitstream Vera Sans-B.fdb" \
	"Bitstream Vera Sans-I.fdb" \
	"Bitstream Vera Sans.fdb" \
	"Bitstream Vera Serif-B.fdb" \
	"Bitstream Vera Serif.fdb"

ICON_MAIN = \
	salasaga-icon.ico

ICON_PNG = \
	salasaga-icon.png

ICONS_PNG = \
	add_highlight.png \
	add_highlight_grayed.png \
	add_image.png \
	add_image_grayed.png \
	add_mouse.png \
	add_mouse_grayed.png \
	add_text.png \
	add_text_grayed.png \
	capture.png \
	capture_grayed.png \
	crop.png \
	crop_grayed.png \
	delete.png \
	delete_grayed.png \
	down_arrow.png \
	down_arrow_grayed.png \
	edit.png \
	edit_grayed.png \
	export_flash.png \
	export_flash_grayed.png \
	import.png \
	import_grayed.png \
	salasaga_logo.png \
	up_arrow.png \
	up_arrow_grayed.png

ICONS_SCALABLE = \
	add_highlight.svg \
	add_highlight_grayed.svg \
	add_image.svg \
	add_image_grayed.svg \
	add_mouse.svg \
	add_mouse_grayed.svg \
	add_text.svg \
	add_text_grayed.svg \
	capture.svg \
	capture_grayed.svg \
	crop.svg \
	crop_grayed.svg \
	delete.svg \
	delete_grayed.svg \
	down_arrow.svg \
	down_arrow_grayed.svg \
	edit.svg \
	edit_grayed.svg \
	export_flash.svg \
	export_flash_grayed.svg \
	import.svg \
	import_grayed.svg \
	up_arrow.svg \
	up_arrow_grayed.svg

ICONS_CONTROL_BAR_PNG = \
	1leftarrow_down.png \
	1leftarrow_over.png \
	1leftarrow_up.png \
	1rightarrow_down.png \
	1rightarrow_over.png \
	1rightarrow_up.png \
	2leftarrow_down.png \
	2leftarrow_over.png \
	2leftarrow_up.png \
	2rightarrow_down.png \
	2rightarrow_over.png \
	2rightarrow_up.png \
	3leftarrow_down.png \
	3leftarrow_over.png \
	3leftarrow_up.png \
	3rightarrow_down.png \
	3rightarrow_over.png \
	3rightarrow_up.png \
	help_down.png \
	help_over.png \
	help_up.png \
	info_down.png \
	info_over.png \
	info_up.png \
	player_pause_down.png \
	player_pause_over.png \
	player_pause_up.png \
	player_stop_down.png \
	player_stop_over.png \
	player_stop_up.png

ICONS_CONTROL_BAR_SCALABLE = \
	1leftarrow_down.svg \
	1leftarrow_over.svg \
	1leftarrow_up.svg \
	1rightarrow_down.svg \
	1rightarrow_over.svg \
	1rightarrow_up.svg \
	2leftarrow_down.svg \
	2leftarrow_over.svg \
	2leftarrow_up.svg \
	2rightarrow_down.svg \
	2rightarrow_over.svg \
	2rightarrow_up.svg \
	3leftarrow_down.svg \
	3leftarrow_over.svg \
	3leftarrow_up.svg \
	3rightarrow_down.svg \
	3rightarrow_over.svg \
	3rightarrow_up.svg \
	help_down.svg \
	help_over.svg \
	help_up.svg \
	info_down.svg \
	info_over.svg \
	info_up.svg \
	player_pause_down.svg \
	player_pause_over.svg \
	player_pause_up.svg \
	player_stop_down.svg \
	player_stop_over.svg \
	player_stop_up.svg

MOUSE_SCALABLE = \
	standard.svg

MOUSE_PNG = \
	standard.png

OFILES = \
	functions/create_menu_bar.o \
	functions/create_resolution_selector.o \
	functions/create_time_line.o \
	functions/create_toolbar.o \
	functions/create_zoom_selector.o \
	functions/disable_layer_toolbar_buttons.o \
	functions/disable_main_toolbar_buttons.o \
	functions/draw_timeline.o \
	functions/enable_layer_toolbar_buttons.o \
	functions/enable_main_toolbar_buttons.o \
	functions/key_bind.o \
	functions/logger_simple.o \
	functions/logger_with_domain.o \
	functions/preferences_load.o \
	functions/project_crop.o \
	functions/project_read.o \
	functions/quit_event.o \
	functions/resolution_selector_changed.o \
	functions/save_preferences_and_exit.o \
	functions/validate_value.o \
	functions/zoom_selector_changed.o \
	functions/cairo/calculate_text_object_size.o \
	functions/cairo/create_cairo_pixbuf_pattern.o \
	functions/callbacks/menu_screenshots_capture_full_screen.o \
	functions/conversion/base64_decode.o \
	functions/conversion/base64_encode.o \
	functions/dialog/display_dialog_empty.o \
	functions/dialog/display_dialog_highlight.o \
	functions/dialog/display_dialog_image.o \
	functions/dialog/display_dialog_mouse.o \
	functions/dialog/display_dialog_save_warning.o \
	functions/dialog/display_dialog_text.o \
	functions/dialog/display_warning.o \
	functions/export/html/export_html_wrapper.o \
	functions/export/swf/export_swf_choose_resolution_index.o \
	functions/export/swf/export_swf_control_bar.o \
	functions/export/swf/export_swf_create_layer_elements.o \
	functions/export/swf/export_swf_create_shape.o \
	functions/export/swf/export_swf_inner.o \
	functions/export/swf/export_swf_process_element.o \
	functions/export/swf/swf_add_mouse_click.o \
	functions/export/swf/swf_shape_from_image_file.o \
	functions/film_strip/create_film_strip.o \
	functions/film_strip/film_strip_create_thumbnail.o \
	functions/film_strip/film_strip_handle_changed.o \
	functions/film_strip/film_strip_handle_released.o \
	functions/film_strip/film_strip_slide_clicked.o \
	functions/film_strip/regenerate_film_strip_thumbnails.o \
	functions/layer/compress_layers.o \
	functions/layer/compress_layers_inner.o \
	functions/layer/get_layer_position.o \
	functions/layer/image_crop.o \
	functions/layer/layer_copy.o \
	functions/layer/layer_delete.o \
	functions/layer/layer_duplicate.o \
	functions/layer/layer_edit.o \
	functions/layer/layer_free.o \
	functions/layer/layer_move_down.o \
	functions/layer/layer_move_up.o \
	functions/layer/layer_new_highlight.o \
	functions/layer/layer_new_highlight_inner.o \
	functions/layer/layer_new_image.o \
	functions/layer/layer_new_image_inner.o \
	functions/layer/layer_new_mouse.o \
	functions/layer/layer_new_mouse_inner.o \
	functions/layer/layer_new_text.o \
	functions/layer/layer_new_text_inner.o \
	functions/layer/layer_paste.o \
	functions/menu/menu_edit_preferences.o \
	functions/menu/menu_enable.o \
	functions/menu/menu_export_swf.o \
	functions/menu/menu_export_layer.o \
	functions/menu/menu_export_slide.o \
	functions/menu/menu_file_close.o \
	functions/menu/menu_file_new.o \
	functions/menu/menu_file_open.o \
	functions/menu/menu_file_save.o \
	functions/menu/menu_file_save_as.o \
	functions/menu/menu_file_save_layer.o \
	functions/menu/menu_file_save_slide.o \
	functions/menu/menu_help_about.o \
	functions/menu/menu_help_forum.o \
	functions/menu/menu_help_register.o \
	functions/menu/menu_help_survey.o \
	functions/menu/menu_help_support.o \
	functions/menu/menu_help_website.o \
	functions/menu/menu_help_wiki.o \
	functions/menu/menu_project_properties.o \
	functions/menu/menu_screenshots_capture.o \
	functions/menu/menu_screenshots_import.o \
	functions/slide/slide_delete.o \
	functions/slide/slide_duration.o \
	functions/slide/slide_free.o \
	functions/slide/slide_insert.o \
	functions/slide/slide_move_bottom.o \
	functions/slide/slide_move_down.o \
	functions/slide/slide_move_top.o \
	functions/slide/slide_move_up.o \
	functions/widgets/time_line.o \
	functions/working_area/calculate_object_boundaries.o \
	functions/working_area/create_working_area.o \
	functions/working_area/detect_collisions.o \
	functions/working_area/draw_bounding_box.o \
	functions/working_area/draw_handle_box.o \
	functions/working_area/draw_highlight_box.o \
	functions/working_area/draw_layer_start_and_end_points.o \
	functions/working_area/draw_resize_handles.o \
	functions/working_area/draw_workspace.o \
	functions/working_area/event_size_allocate_received.o \
	functions/working_area/working_area_button_press_event.o \
	functions/working_area/working_area_button_release_event.o \
	functions/working_area/working_area_expose_event.o \
	functions/working_area/working_area_motion_notify_event.o \
	salasaga.o

SOUNDS = \
	mouse_single_click.mp3 \
	mouse_double_click.mp3 \
	mouse_triple_click.mp3

all: salasaga

create_menu_bar.o:
	$(CC) $(CFLAGS) -c create_menu_bar.c -o create_menu_bar.o

create_resolution_selector.o:
	$(CC) $(CFLAGS) -c create_resolution_selector.c -o create_resolution_selector.o

create_time_line.o:
	$(CC) $(CFLAGS) -c create_time_line.c -o create_time_line.o

create_toolbar.o:
	$(CC) $(CFLAGS) -c create_toolbar.c -o create_toolbar.o

create_zoom_selector.o:
	$(CC) $(CFLAGS) -c create_zoom_selector.c -o create_zoom_selector.o

disable_layer_toolbar_buttons.o:
	$(CC) $(CFLAGS) -c disable_layer_toolbar_buttons.c -o disable_layer_toolbar_buttons.o

disable_main_toolbar_buttons.o:
	$(CC) $(CFLAGS) -c disable_main_toolbar_buttons.c -o disable_main_toolbar_buttons.o

draw_timeline.o:
	$(CC) $(CFLAGS) -c draw_timeline.c -o draw_timeline.o

enable_layer_toolbar_buttons.o:
	$(CC) $(CFLAGS) -c enable_layer_toolbar_buttons.c -o enable_layer_toolbar_buttons.o

enable_main_toolbar_buttons.o:
	$(CC) $(CFLAGS) -c enable_main_toolbar_buttons.c -o enable_main_toolbar_buttons.o

key_bind.o:
	$(CC) $(CFLAGS) -c key_bind.c -o key_bind.o

logger_simple.o:
	$(CC) $(CFLAGS) -c logger_simple.c -o logger_simple.o

logger_with_domain.o:
	$(CC) $(CFLAGS) -c logger_with_domain.c -o logger_with_domain.o

preferences_load.o:
	$(CC) $(CFLAGS) -c preferences_load.c -o preferences_load.o

project_crop.o:
	$(CC) $(CFLAGS) -c project_crop.c -o project_crop.o

project_read.o:
	$(CC) $(CFLAGS) -c project_read.c -o project_read.o

quit_event.o:
	$(CC) $(CFLAGS) -c quit_event.c -o quit_event.o

resolution_selector_changed.o:
	$(CC) $(CFLAGS) -c resolution_selector_changed.c -o resolution_selector_changed.o

save_preferences_and_exit.o:
	$(CC) $(CFLAGS) -c save_preferences_and_exit.c -o save_preferences_and_exit.o

validate_value.o:
	$(CC) $(CFLAGS) -c validate_value.c -o validate_value.o

zoom_selector_changed.o:
	$(CC) $(CFLAGS) -c zoom_selector_changed.c -o zoom_selector_changed.o

cairo/calculate_text_object_size.o:
	$(CC) $(CFLAGS) -c cairo/calculate_text_object_size.c -o cairo/calculate_text_object_size.o

cairo/create_cairo_pixbuf_pattern.o:
	$(CC) $(CFLAGS) -c cairo/create_cairo_pixbuf_pattern.c -o cairo/create_cairo_pixbuf_pattern.o

callbacks/menu_screenshots_capture_full_screen.o:
	$(CC) $(CFLAGS) -c callbacks/menu_screenshots_capture_full_screen.c -o callbacks/menu_screenshots_capture_full_screen.o

conversion/base64_decode.o:
	$(CC) $(CFLAGS) -c conversion/base64_decode.c -o conversion/base64_decode.o

conversion/base64_encode.o:
	$(CC) $(CFLAGS) -c conversion/base64_encode.c -o conversion/base64_encode.o

dialog/display_dialog_empty.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_empty.c -o dialog/display_dialog_empty.o

dialog/display_dialog_highlight.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_highlight.c -o dialog/display_dialog_highlight.o

dialog/display_dialog_image.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_image.c -o dialog/display_dialog_image.o

dialog/display_dialog_mouse.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_mouse.c -o dialog/display_dialog_mouse.o

dialog/display_dialog_save_warning.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_save_warning.c -o dialog/display_dialog_save_warning.o

dialog/display_dialog_text.o:
	$(CC) $(CFLAGS) -c dialog/display_dialog_text.c -o dialog/display_dialog_text.o

dialog/display_warning.o:
	$(CC) $(CFLAGS) -c dialog/display_warning.c -o dialog/display_warning.o

export/html/export_html_wrapper.o:
	$(CC) $(CFLAGS) -c export/html/export_html_wrapper.c -o export/html/export_html_wrapper.o

export/swf/export_swf_choose_resolution_index.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_choose_resolution_index.c -o export/swf/export_swf_choose_resolution_index.o

export/swf/export_swf_control_bar.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_control_bar.c -o export/swf/export_swf_control_bar.o

export/swf/export_swf_create_layer_elements.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_create_layer_elements.c -o export/swf/export_swf_create_layer_elements.o

export/swf/export_swf_create_shape.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_create_shape.c -o export/swf/export_swf_create_shape.o

export/swf/export_swf_inner.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_inner.c -o export/swf/export_swf_inner.o

export/swf/export_swf_process_element.o:
	$(CC) $(CFLAGS) -c export/swf/export_swf_process_element.c -o export/swf/export_swf_process_element.o

export/swf/swf_add_mouse_click.o:
	$(CC) $(CFLAGS) -c export/swf/swf_add_mouse_click.c -o export/swf/swf_add_mouse_click.o

export/swf/swf_shape_from_image_file.o:
	$(CC) $(CFLAGS) -c export/swf/swf_shape_from_image_file.c -o export/swf/swf_shape_from_image_file.o

film_strip/create_film_strip.o:
	$(CC) $(CFLAGS) -c film_strip/create_film_strip.c -o film_strip/create_film_strip.o

film_strip/film_strip_create_thumbnail.o:
	$(CC) $(CFLAGS) -c film_strip/film_strip_create_thumbnail.c -o film_strip/film_strip_create_thumbnail.o

film_strip/film_strip_handle_changed.o:
	$(CC) $(CFLAGS) -c film_strip/film_strip_handle_changed.c -o film_strip/film_strip_handle_changed.o

film_strip/film_strip_handle_released.o:
	$(CC) $(CFLAGS) -c film_strip/film_strip_handle_released.c -o film_strip/film_strip_handle_released.o

film_strip/film_strip_slide_clicked.o:
	$(CC) $(CFLAGS) -c film_strip/film_strip_slide_clicked.c -o film_strip/film_strip_slide_clicked.o

film_strip/regenerate_film_strip_thumbnails.o:
	$(CC) $(CFLAGS) -c film_strip/regenerate_film_strip_thumbnails.c -o film_strip/regenerate_film_strip_thumbnails.o

layer/compress_layers.o:
	$(CC) $(CFLAGS) -c layer/compress_layers.c -o layer/compress_layers.o

layer/compress_layers_inner.o:
	$(CC) $(CFLAGS) -c layer/compress_layers_inner.c -o compress_layers_inner.o

layer/get_layer_position.o:
	$(CC) $(CFLAGS) -c layer/get_layer_position.c -o layer/get_layer_position.o

layer/image_crop.o:
	$(CC) $(CFLAGS) -c layer/image_crop.c -o layer/image_crop.o

layer/layer_copy.o:
	$(CC) $(CFLAGS) -c layer/layer_copy.c -o layer/layer_copy.o

layer/layer_delete.o:
	$(CC) $(CFLAGS) -c layer/layer_delete.c -o layer/layer_delete.o

layer/layer_duplicate.o:
	$(CC) $(CFLAGS) -c layer/layer_duplicate.c -o layer/layer_duplicate.o

layer/layer_edit.o:
	$(CC) $(CFLAGS) -c layer/layer_edit.c -o layer/layer_edit.o

layer/layer_free.o:
	$(CC) $(CFLAGS) -c layer/layer_free.c -o layer/layer_free.o

layer/layer_move_down.o:
	$(CC) $(CFLAGS) -c layer/layer_move_down.c -o layer/layer_move_down.o

layer/layer_move_up.o:
	$(CC) $(CFLAGS) -c layer/layer_move_up.c -o layer/layer_move_up.o

layer/layer_new_highlight.o:
	$(CC) $(CFLAGS) -c layer/layer_new_highlight.c -o layer/layer_new_highlight.o

layer/layer_new_highlight_inner.o:
	$(CC) $(CFLAGS) -c layer/layer_new_highlight_inner.c -o layer/layer_new_highlight_inner.o

layer/layer_new_image.o:
	$(CC) $(CFLAGS) -c layer/layer_new_image.c -o layer/layer_new_image.o

layer/layer_new_image_inner.o:
	$(CC) $(CFLAGS) -c layer/layer_new_image_inner.c -o layer/layer_new_image_inner.o

layer/layer_new_mouse.o:
	$(CC) $(CFLAGS) -c layer/layer_new_mouse.c -o layer/layer_new_mouse.o

layer/layer_new_mouse_inner.o:
	$(CC) $(CFLAGS) -c layer/layer_new_mouse_inner.c -o layer/layer_new_mouse_inner.o

layer/layer_new_text.o:
	$(CC) $(CFLAGS) -c layer/layer_new_text.c -o layer/layer_new_text.o

layer/layer_new_text_inner.o:
	$(CC) $(CFLAGS) -c layer/layer_new_text_inner.c -o layer/layer_new_text_inner.o

layer/layer_paste.o:
	$(CC) $(CFLAGS) -c layer/layer_paste.c -o layer/layer_paste.o

menu/menu_edit_preferences.o:
	$(CC) $(CFLAGS) -c menu/menu_edit_preferences.c -o menu/menu_edit_preferences.o

menu/menu_enable.o:
	$(CC) $(CFLAGS) -c menu/menu_enable.c -o menu/menu_enable.o

menu/menu_export_swf.o:
	$(CC) $(CFLAGS) -c menu/menu_export_swf.c -o menu/menu_export_swf.o

menu/menu_export_layer.o:
	$(CC) $(CFLAGS) -c menu/menu_export_layer.c -o menu/menu_export_layer.o

menu/menu_export_slide.o:
	$(CC) $(CFLAGS) -c menu/menu_export_slide.c -o menu/menu_export_slide.o

menu/menu_file_close.o:
	$(CC) $(CFLAGS) -c menu/menu_file_close.c -o menu/menu_file_close.o

menu/menu_file_new.o:
	$(CC) $(CFLAGS) -c menu/menu_file_new.c -o menu/menu_file_new.o

menu/menu_file_open.o:
	$(CC) $(CFLAGS) -c menu/menu_file_open.c -o menu/menu_file_open.o

menu/menu_file_save.o:
	$(CC) $(CFLAGS) -c menu/menu_file_save.c -o menu/menu_file_save.o

menu/menu_file_save_as.o:
	$(CC) $(CFLAGS) -c menu/menu_file_save_as.c -o menu/menu_file_save_as.o

menu/menu_file_save_layer.o:
	$(CC) $(CFLAGS) -c menu/menu_file_save_layer.c -o menu/menu_file_save_layer.o

menu/menu_file_save_slide.o:
	$(CC) $(CFLAGS) -c menu/menu_file_save_slide.c -o menu/menu_file_save_slide.o

menu/menu_help_about.o:
	$(CC) $(CFLAGS) -c menu/menu_help_about.c -o menu/menu_help_about.o

menu/menu_help_forum.o:
	$(CC) $(CFLAGS) -c menu/menu_help_register.c -o menu/menu_help_register.o

menu/menu_help_register.o:
	$(CC) $(CFLAGS) -c menu/menu_help_register.c -o menu/menu_help_register.o

menu/menu_help_support.o:
	$(CC) $(CFLAGS) -c menu/menu_help_register.c -o menu/menu_help_register.o

menu/menu_help_survey.o:
	$(CC) $(CFLAGS) -c menu/menu_help_survey.c -o menu/menu_help_survey.o

menu/menu_help_website.o:
	$(CC) $(CFLAGS) -c menu/menu_help_website.c -o menu/menu_help_website.o

menu/menu_help_wiki.o:
	$(CC) $(CFLAGS) -c menu/menu_help_register.c -o menu/menu_help_register.o

menu/menu_project_properties.o:
	$(CC) $(CFLAGS) -c menu/menu_project_properties.c -o menu/menu_project_properties.o

menu/menu_screenshots_capture.o:
	$(CC) $(CFLAGS) -c menu/menu_screenshots_capture.c -o menu/menu_screenshots_capture.o

menu/menu_screenshots_import.o:
	$(CC) $(CFLAGS) -c menu/menu_screenshots_import.c -o menu/menu_screenshots_import.o

slide/slide_delete.o:
	$(CC) $(CFLAGS) -c slide/slide_delete.c -o slide/slide_delete.o

slide/slide_duration.o:
	$(CC) $(CFLAGS) -c slide/slide_duration.c -o slide/slide_duration.o

slide/slide_free.o:
	$(CC) $(CFLAGS) -c slide/slide_free.c -o slide/slide_free.o

slide/slide_insert.o:
	$(CC) $(CFLAGS) -c slide/slide_insert.c -o slide/slide_insert.o

slide/slide_move_bottom.o:
	$(CC) $(CFLAGS) -c slide/slide_move_bottom.c -o slide/slide_move_bottom.o

slide/slide_move_down.o:
	$(CC) $(CFLAGS) -c slide/slide_move_down.c -o slide/slide_move_down.o

slide/slide_move_top.o:
	$(CC) $(CFLAGS) -c slide/slide_move_top.c -o slide/slide_move_top.o

slide/slide_move_up.o:
	$(CC) $(CFLAGS) -c slide/slide_move_up.c -o slide/slide_move_up.o

widgets/time_line.o:
	$(CC) $(CFLAGS) -c widgets/time_line.c -o widgets/time_line.o

working_area/calculate_object_boundaries.o:
	$(CC) $(CFLAGS) -c working_area/calculate_object_boundaries.c -o working_area/calculate_object_boundaries.o

working_area/create_working_area.o:
	$(CC) $(CFLAGS) -c working_area/create_working_area.c -o working_area/create_working_area.o

working_area/detect_collisions.o:
	$(CC) $(CFLAGS) -c working_area/detect_collisions.c -o working_area/detect_collisions.o

working_area/draw_bounding_box.o:
	$(CC) $(CFLAGS) -c working_area/draw_bounding_box.c -o working_area/draw_bounding_box.o

working_area/draw_handle_box.o:
	$(CC) $(CFLAGS) -c working_area/draw_handle_box.c -o working_area/draw_handle_box.o

working_area/draw_highlight_box.o:
	$(CC) $(CFLAGS) -c working_area/draw_highlight_box.c -o working_area/draw_highlight_box.o

working_area/draw_layer_start_and_end_points.o:
	$(CC) $(CFLAGS) -c working_area/draw_layer_start_and_end_points.c -o working_area/draw_layer_start_and_end_points.o

working_area/draw_resize_handles.o:
	$(CC) $(CFLAGS) -c working_area/draw_resize_handles.c -o working_area/draw_resize_handles.o

working_area/draw_workspace.o:
	$(CC) $(CFLAGS) -c working_area/draw_workspace.c -o working_area/draw_workspace.o

working_area/event_size_allocate_received.o:
	$(CC) $(CFLAGS) -c working_area/event_size_allocate_received.c -o working_area/event_size_allocate_received.o

working_area/working_area_button_press_event.o:
	$(CC) $(CFLAGS) -c working_area/working_area_button_press_event.c -o working_area/working_area_button_press_event.o

working_area/working_area_button_release_event.o:
	$(CC) $(CFLAGS) -c working_area/working_area_button_release_event.c -o working_area/working_area_button_release_event.o

working_area/working_area_expose_event.o:
	$(CC) $(CFLAGS) -c working_area/working_area_expose_event.c -o working_area/working_area_expose_event.o

working_area/working_area_motion_notify_event.o:
	$(CC) $(CFLAGS) -c working_area/working_area_motion_notify_event.c -o working_area/working_area_motion_notify_event.o

salasaga.o:
	$(CC) $(CFLAGS) -c salasaga.c -o salasaga.o

salasaga: $(OFILES)
	$(CC) $(CFLAGS) $(OFILES) $(LDFLAGS) $(LIBS) -o salasaga

install:
	$(INSTALL) -d $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) -m 0755 salasaga $(DESTDIR)$(bindir)
	$(INSTALL) -d $(DESTDIR)$(datadir)/applications/
	$(INSTALL_DATA) $(DESKTOP_FILE) $(DESTDIR)$(datadir)/applications/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/fonts/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/fdb
	$(INSTALL) -d $(DESTDIR)$(datadir)/pixmaps/
	cd images; $(INSTALL_DATA) $(ICON_MAIN) $(DESTDIR)$(datadir)/salasaga/icons/
	cd images; $(INSTALL_DATA) $(ICON_PNG) $(DESTDIR)$(datadir)/pixmaps/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/scalable/
	cd images; $(INSTALL_DATA) $(ICONS_SCALABLE) $(DESTDIR)$(datadir)/salasaga/icons/scalable/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/scalable/control_bar/
	cd images; cd control_bar; $(INSTALL_DATA) $(ICONS_CONTROL_BAR_SCALABLE) $(DESTDIR)$(datadir)/salasaga/icons/scalable/control_bar
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/scalable/pointers/
	cd images; cd pointers; $(INSTALL_DATA) $(MOUSE_SCALABLE) $(DESTDIR)$(datadir)/salasaga/icons/scalable/pointers/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/72x72/
	cd images; $(INSTALL_DATA) $(ICONS_PNG) $(DESTDIR)$(datadir)/salasaga/icons/72x72/
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/72x72/control_bar/
	cd images; cd control_bar; $(INSTALL_DATA) $(ICONS_CONTROL_BAR_PNG) $(DESTDIR)$(datadir)/salasaga/icons/72x72/control_bar
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/icons/72x72/pointers/
	cd images; cd pointers; $(INSTALL_DATA) $(MOUSE_PNG) $(DESTDIR)$(datadir)/salasaga/icons/72x72/pointers/
	cd fonts; cd BitstreamVera; cd fdb; $(INSTALL_DATA) $(FONT_BITSTREAM_VERA_FDB) $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/fdb
	$(INSTALL) -d $(DESTDIR)$(datadir)/salasaga/sounds/
	cd sounds; $(INSTALL_DATA) $(SOUNDS) $(DESTDIR)$(datadir)/salasaga/sounds/

uninstall:
	if [ -f "$(DESTDIR)$(bindir)/salasaga" ]; then \
		rm -f $(DESTDIR)$(bindir)/salasaga; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/fdb" ]; then \
		cd $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/fdb/; \
		rm -f $(FONT_BITSTREAM_VERA_FDB); \
		rmdir $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/fdb/; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera" ]; then \
		rmdir $(DESTDIR)$(datadir)/salasaga/fonts/BitstreamVera/; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/fonts" ]; then \
		rmdir $(DESTDIR)$(datadir)/salasaga/fonts/; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/scalable" ]; then \
		if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/scalable/control_bar" ]; then \
			cd $(DESTDIR)$(datadir)/salasaga/icons/scalable/control_bar/; \
			rm -f $(ICONS_CONTROL_BAR_SCALABLE); \
			rmdir $(DESTDIR)$(datadir)/salasaga/icons/scalable/control_bar/; \
		fi; \
		if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/scalable/pointers" ]; then \
			cd $(DESTDIR)$(datadir)/salasaga/icons/scalable/pointers/; \
			rm -f $(MOUSE_SCALABLE); \
			rmdir $(DESTDIR)$(datadir)/salasaga/icons/scalable/pointers/; \
		fi; \
		cd $(DESTDIR)$(datadir)/salasaga/icons/scalable/; \
		rm -f $(ICONS_SCALABLE); \
		rmdir $(DESTDIR)$(datadir)/salasaga/icons/scalable/; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/72x72" ]; then \
		if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/72x72/control_bar" ]; then \
			cd $(DESTDIR)$(datadir)/salasaga/icons/72x72/control_bar/; \
			rm -f $(ICONS_CONTROL_BAR_PNG); \
			rmdir $(DESTDIR)$(datadir)/salasaga/icons/72x72/control_bar/; \
		fi; \
		if [ -d "$(DESTDIR)$(datadir)/salasaga/icons/72x72/pointers" ]; then \
			cd $(DESTDIR)$(datadir)/salasaga/icons/72x72/pointers/; \
			rm -f $(MOUSE_PNG); \
			rmdir $(DESTDIR)$(datadir)/salasaga/icons/72x72/pointers/; \
		fi; \
		cd $(DESTDIR)$(datadir)/salasaga/icons/72x72/; \
		rm -f $(ICONS_PNG); \
		rmdir $(DESTDIR)$(datadir)/salasaga/icons/72x72/; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/sounds" ]; then \
		cd $(DESTDIR)$(datadir)/salasaga/sounds/; \
		rm -f $(SOUNDS); \
		rmdir $(DESTDIR)$(datadir)/salasaga/sounds; \
	fi

	if [ -f "$(DESTDIR)$(datadir)/salasaga/icons/$(ICON_MAIN)" ]; then \
		rm -f $(DESTDIR)$(datadir)/salasaga/icons/$(ICON_MAIN); \
	fi

	if [ -f "$(DESTDIR)$(datadir)/pixmaps/$(ICON_PNG)" ]; then \
		rm -f $(DESTDIR)$(datadir)/pixmaps/$(ICON_PNG); \
		rmdir $(DESTDIR)$(datadir)/pixmaps; \
	fi

	if [ -f "$(DESTDIR)$(datadir)/applications/$(DESKTOP_FILE)" ]; then \
		rm -f $(DESTDIR)$(datadir)/applications/$(DESKTOP_FILE); \
		rmdir $(DESTDIR)$(datadir)/applications; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga/icons" ]; then \
		rmdir $(DESTDIR)$(datadir)/salasaga/icons; \
	fi

	if [ -d "$(DESTDIR)$(datadir)/salasaga" ]; then \
		rmdir $(DESTDIR)$(datadir)/salasaga; \
	fi

	if [ -d "$(DESTDIR)$(bindir)" ]; then \
		rmdir --ignore-fail-on-non-empty $(DESTDIR)$(bindir); \
	fi

	if [ -d "$(DESTDIR)$(datadir)" ]; then \
		rmdir --ignore-fail-on-non-empty $(DESTDIR)$(datadir); \
	fi

clean:
	rm -f $(OFILES)
	rm -f salasaga salasaga.exe

distclean: clean
	rm -Rf Rules.make config.make Makefile.config autom4te.cache config.log config.status configure

maintainer-clean: distclean
	rm -f configure
